### ISSUE TITLE
Pasteur should appear clearly as an organiser

### ISSUE THREAD

**Issue by GaelVaroquaux** [paris-saclay-cds/ramp-autism-website#1]
Pasteur and CDS should be displayed at the same level of importance.

**Comment by glemaitre** [comment]
@GaelVaroquaux Can you check the organizers section to know if this is enough?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux Can you check the organizers section to know if this is enough?

It's good. If we put brainhack, we'll have to contact them, and involve
them (I am in favor of this).

**Comment by GaelVaroquaux** [comment]
Should we have names? I suspect so. It would be useful.

**Comment by glemaitre** [comment]
I added couple of people. Check if I did not forgot someone

**Comment by glemaitre** [comment]
Basically, I am unsure on the side of Pasteur if we did not forgot somebody.
